#!/usr/bin/env python
# coding:utf-8
from time import time


def bubbleSort(nums):
    flag=True
    for i in range(len(nums)-1): #i是冒泡的总次数
        while flag:
            flag=False
            for j in range(len(nums)-1-i):
                #这个程序的冒泡每次都让最大的沉到最底下
                #所以每次沉下去的那个数字就不用管了所以是lennums-1-
                if nums[j]>nums[j+1] :
                    nums[j+1],nums[j]=nums[j],nums[j+1]
                    flag = True
    return nums
t=time()
nums = [5,3,45,6,8,2,1,3,77,33,55,77,888,9,999]
print bubbleSort(nums)
print time() - t
